tap_install:
    sensitive_values:
        shared:
            image_registry:
                project_path: ENC[AES256_GCM,data:1UlmrrW6ybGCNz9PxUtak8UEfIDKti2h2I/R,iv:WP6AzdIJoJY3X0mBZAxqYv0ajiVQnnpwiBSh8ZYKNu4=,tag:UN6O3g9AEUUP502dXxTaQA==,type:str]
                username: ENC[AES256_GCM,data:H2nqpBmbPA==,iv:hYPCOfVcA8K9F+Df2FENfZfWvjN9iJ+UxjHpc0fxbls=,tag:od3oHZF6T2eIgvNTSySzYQ==,type:str]
                password: ENC[AES256_GCM,data:e6PZNRz9KIld0Lb7zPgTS09YcMuKLZrAKBE23uVzhhKisKSwTJtVhuxLceDUruw1lgRvVQ==,iv:m9ayVsvCeJd1xwVBXMT+SG1CV3NSS+PVdvOqbrwfiwQ=,tag:Ypw+SBBdBUpOiiZPLt6ySg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15v69n9lqpkegn9mc76eut38saxlpx7y8q7thldfs73jdkkgctqksuj69ep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT253ODBvVk5ONWlIRjJF
            Qkt4UEpmR3VNR0I5bHF3c0F2ZHRZaWthM1JnCldPQW9BYmhrdmo1TjBuL3RpbVYr
            VjN4UHJYT0UzV2VMM1ZhTXJMc2tsSEEKLS0tIEdtZVljemdBdFZnQ0V4cmxJYmVW
            RTNJVTQvYVphMlZJYWlIaXRjdXhaT1EKxV3VbHzmnKPkVY+ROKadkK1yVuWx0hXL
            pqwNuKbMgmXFpzPbem5fC08yYFhEAVTuUAHqY+q4dhPypOyEoYD1sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-12T15:20:36Z"
    mac: ENC[AES256_GCM,data:9kx8SEgPrvgqOsYazB9HRJ4dY+865+x8PVYuklRbiOoyn0jEWq2vYuPGItaVlfmHMlmYcKEAr5SrXJlT1Z9LOzsfMzqvOU5nrPTKXkCHtKnDNOmjBpcemCI4e7EARwnEVg/tVk5fos3bH+Gl9V9/Ckx7o1b+XiUCwVIcBNP2UM8=,iv:XIcFFdfMtHIKRd7lAiTwuKZO1s6XrMHCfNgUop4nFDg=,tag:hzpZQ/NuzNY2dXiv9BNu5w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
